package consts

import (
	"time"

	"github.com/sirupsen/logrus"
)

// DefaultAPIHTTPHost const ...
const DefaultAPIHTTPHost = "localhost"

// DefaultAPIHTTPPort const ...
const DefaultAPIHTTPPort = 7000

// DefaultAPIHTTPReadTimeout const ...
const DefaultAPIHTTPReadTimeout = 15 * time.Second

// DefaultAPIHTTPWriteTimeout const ...
const DefaultAPIHTTPWriteTimeout = 15 * time.Second

// DefaultAppMode const ...
const DefaultAppMode = "local"

// DefaultDatabaseDriver const ...
const DefaultDatabaseDriver = "mysql"

// DefaultDatabaseHostname const ...
const DefaultDatabaseHostname = "localhost"

// DefaultDatabaseUsername const ...
const DefaultDatabaseUsername = "username"

// DefaultDatabasePassword const ...
const DefaultDatabasePassword = "password"

// DefaultDatabaseDBName const ...
const DefaultDatabaseDBName = "database"

// DefaultDatabaseDBPort const ...
const DefaultDatabaseDBPort = 3306

// DefaultLoggerDebug const ...
const DefaultLoggerDebug = false

// DefaultLoggerFileFormatterDisableColors const ...
const DefaultLoggerFileFormatterDisableColors = true

// DefaultLoggerLevel const ...
const DefaultLoggerLevel = logrus.WarnLevel

// DefaultLoggerLinkName const ...
const DefaultLoggerLinkName = "log"

// DefaultLoggerMaxAge const ...
const DefaultLoggerMaxAge = 365 * 24 * time.Hour

// DefaultLoggerPattern const ...
const DefaultLoggerPattern = ".%Y-%m-%d_%H:%M"

// DefaultLoggerReportCaller const ...
const DefaultLoggerReportCaller = true

// DefaultLoggerTimezone const ...
const DefaultLoggerTimezone = "Europe/Moscow"

// DefaultLoggerTtyFormatterForceColors const ...
const DefaultLoggerTtyFormatterForceColors = true

// DefaultLoggerTtyFormatterFullTimestamp const ...
const DefaultLoggerTtyFormatterFullTimestamp = true

// NotDefaultLoggerLevel const ...
const NotDefaultLoggerLevel = logrus.DebugLevel

// DefaultPublishConfigDir const ...
const DefaultPublishConfigDir = "config"

// DefaultPublishLogsDir const ...
const DefaultPublishLogsDir = "logs"

// DefaultPublishMigrationsDir const ...
const DefaultPublishMigrationsDir = "migrations"

// DefaultPublishDir const ...
const DefaultPublishDir = "publish"

// DefaultPublishFile const ...
const DefaultPublishFile = "publish.toml"
